# Generated by Django 3.1.1 on 2020-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поля')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('radio', 'Радио кнопка'), ('dropdown', 'Выпадающий список'), ('date', 'Поле даты'), ('checkbox', 'Чекбокс')], max_length=31, verbose_name='Тип поля')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Тело формы')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поясняющий текст')),
                ('required', models.BooleanField(default=False, verbose_name='обязательно ли поле')),
            ],
            options={
                'verbose_name': 'Поле справки',
                'verbose_name_plural': 'Поля справок',
            },
        ),
        migrations.CreateModel(
            name='FormBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поясняющий текст для справки')),
                ('form_fields', models.ManyToManyField(related_name='form_body', to='api.FormField', verbose_name='Поля справки')),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
                'default_related_name': 'form_bodies',
            },
        ),
    ]
