# Generated by Django 3.1.1 on 2020-10-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('is_regulator', models.BooleanField(default=True, verbose_name='Департамент утвердителей?')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название регламента')),
                ('text', models.TextField(verbose_name='Текст регламента')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Версия регламентов')),
                ('approved', models.ManyToManyField(related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='Одобрившие регламент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_regulations', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('departments', models.ManyToManyField(related_name='regulations', to='api.Department', verbose_name='Департаменты')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_regulations', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлена')),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': 'Регламенты',
                'default_related_name': 'regulations',
            },
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('report', models.TextField(verbose_name='Сообщение по правке')),
                ('paragraph', models.CharField(max_length=32, verbose_name='Абзац для правки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.regulations', verbose_name='Регламент')),
            ],
            options={
                'verbose_name': 'Правка',
                'verbose_name_plural': 'Правки',
                'default_related_name': 'revisions',
            },
        ),
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('patronymic_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли пользователь')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.department', verbose_name='Департамент')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
