# Generated by Django 3.1.1 on 2020-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulations',
            options={'default_related_name': 'regulations', 'ordering': ['-created_at'], 'verbose_name': 'Регламент', 'verbose_name_plural': 'Регламенты'},
        ),
        migrations.AddField(
            model_name='regulations',
            name='label',
            field=models.TextField(default='', verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='version_history_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='Номер истории'),
        ),
    ]
