# Generated by Django 3.1.1 on 2020-10-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20201003_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='approved',
            field=models.ManyToManyField(blank=True, null=True, related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='Одобрившие регламент'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_regulations', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_regulations', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлена'),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='version',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Версия регламентов'),
        ),
    ]
