# Generated by Django 3.1.1 on 2020-10-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormBody',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
