# Generated by Django 3.1.1 on 2020-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201002_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='noname', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=False, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='no middle name', max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='employee', max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
