# Generated by Django 3.1.1 on 2020-10-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20201003_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='approved',
            field=models.ManyToManyField(blank=True, related_name='approved', to=settings.AUTH_USER_MODEL, verbose_name='Одобрившие регламент'),
        ),
    ]
