# Generated by Django 3.1.1 on 2020-10-02 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20201002_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userr',
        ),
    ]
