# Generated by Django 3.1.1 on 2020-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201003_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulations',
            name='text',
        ),
        migrations.AddField(
            model_name='regulations',
            name='text1',
            field=models.TextField(default='', verbose_name='Текст 1 раздела'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='text2',
            field=models.TextField(default='', verbose_name='Текст 2 раздела'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='text3',
            field=models.TextField(default='', verbose_name='Текст 3 раздела'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='text4',
            field=models.TextField(default='', verbose_name='Текст 4 раздела'),
        ),
        migrations.AddField(
            model_name='regulations',
            name='text5',
            field=models.TextField(default='', verbose_name='Текст 5 раздела'),
        ),
        migrations.AddField(
            model_name='revisions',
            name='regulation_part',
            field=models.CharField(choices=[('text1', 'text1'), ('text2', 'text2'), ('text3', 'text3'), ('text4', 'text4'), ('text5', 'text5'), ('label', 'label')], default='text1', max_length=32),
        ),
    ]
