# Generated by Django 3.1.1 on 2020-10-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_revisions_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisions',
            name='html_selection',
            field=models.TextField(blank=True, null=True, verbose_name='Выделенный текст для правки'),
        ),
    ]
