# Generated by Django 3.1.1 on 2020-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_revisions_html_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisions',
            name='is_marked_solved',
            field=models.BooleanField(default=False, verbose_name='Отмечен ли как решенный'),
        ),
    ]
