# Generated by Django 3.1.1 on 2020-10-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_revisions_is_marked_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='version',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Версия регламентов'),
        ),
    ]
