# Generated by Django 3.1.1 on 2020-10-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201003_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulations',
            options={'default_related_name': 'regulations', 'verbose_name': 'Регламент', 'verbose_name_plural': 'Регламенты'},
        ),
    ]
