# Generated by Django 3.1.1 on 2020-10-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201003_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_file', models.FileField(max_length=5000, upload_to='', verbose_name='файл приложения')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.regulations', verbose_name='Регламент')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
                'default_related_name': 'applications',
            },
        ),
    ]
