# Generated by Django 3.1.1 on 2020-10-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisions',
            name='secret_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='app_file',
            field=models.FileField(max_length=5000, upload_to='', verbose_name='Файл приложения'),
        ),
    ]
