# Generated by Django 3.1.1 on 2020-10-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201003_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='allow_send_info_emails',
            field=models.BooleanField(default=False, verbose_name='Позволять присылать информационные емейлы'),
        ),
    ]
