# Generated by Django 3.1.1 on 2020-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_revisions_default_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulations',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Устарел ли регламент?'),
        ),
    ]
